// leave off @2x/@3x
const images = {
    banner: require('@Images/banner.png'),
    logo: require("@Images/logo.png"),
    email: require("@Images/email.png"),
    lock: require("@Images/lock.png"),
    phone: require("@Images/phone.png"),
    close: require("@Images/close.png"),
    back: require("@Images/back.png"),
    done: require("@Images/done.png"),
    male: require("@Images/male.png"),
    female: require("@Images/female.png"),
    selectMale: require("@Images/selectMale.png"),
    selectFemale: require("@Images/selectFemale.png"),
    profile: require("@Images/profile.png"),
    eye: require("@Images/eye.png"),
    hide: require("@Images/hide.png"),
    calendar: require("@Images/calendar.png"),
    call: require("@Images/call.png"),
    check: require("@Images/check.png"),
    uncheck: require("@Images/uncheck.png"),
    dropdown: require("@Images/dropdown.png"),
    filter: require("@Images/filter.png"),
    pin: require("@Images/select.png"),
};
export default images;
